version: '3.8'

networks:
  tasha-network:
    driver: bridge

services:
  apache:
    image: httpd:2.4.57-bullseye
    ports:
      - 80:80
    networks:
      - tasha-network

  mysql:
    image: mysql:8.0.33
    env_file:
      - configuration.env
    ports:
      - 3306:3306
    networks:
      - tasha-network
    volumes:
      - mysql-data:/data/db

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - tasha-network

  mongo:
    image: mongo:4.0.28-xenial
    env_file:
      - configuration.env
    ports:
      - 27017:27017
    networks:
      - tasha-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - tasha-network

volumes:
  mongo-data:
    name: mongo-data
  mysql-data:
    name: mysql-data